{% metadata_file .yamato/project.metafile %}
---

{% for project in projects -%}
{% for editor in test_editors -%}
{% for platform in test_platforms -%}
build_{{ project.name }}_{{ editor }}_{{ platform.name }}:
  name : Build Project {{ project.name }} - {{ editor }} on {{ platform.name }}
  agent:
    type: {{ platform.type }}
    image: {{ platform.image }}
    flavor: {{ platform.flavor}}
  commands:
    - echo "success!"
{% endfor -%}
{% endfor -%}
{% endfor -%}


# Run all relevant tasks when a pull request targeting the develop
# branch is created or updated. Currently only mlapi package tests are
# enabled, since the others are missing test coverage and will fail CI.
develop_pull_request_trigger:
  name: Develop Branch Triggers
  dependencies:
{% for project in projects -%}
{% for editor in test_editors -%}
{% for platform in test_platforms -%}
    - .yamato/build.yml#build_{{ project.name }}_{{ editor }}_{{ platform.name }}
{% endfor -%}
{% endfor -%}
{% endfor -%}
  triggers:
    cancel_old_ci: true
    pull_requests:
    - targets:
        only:
          - "main"
          - "develop"